version: 2

ANCHORS:
 node_steps: &node_steps
   steps:
     - checkout
     - run: npm install
     # Check whether "run build" is successful
     - run: npm run build

jobs:
  node_10:
    docker:
      - image: circleci/node:10
    <<: *node_steps
  
  node_8:
    docker:
      - image: circleci/node:8
    <<: *node_steps
  
  node_6:
    docker:
      - image: circleci/node:6
    <<: *node_steps

  gh_page_deploy:
    docker:
      - image: circleci/node:10
    environment:
      GIT_AUTHOR_EMAIL: nwtgck.bee@gmail.com
      GIT_AUTHOR_NAME: "Bee Bot"
      GIT_URL: https://${GITHUB_TOKEN}@github.com/nwtgck/trans-docs.git
    steps:
      - checkout
      # Setting to push as @bee-bot
      - run: git remote set-url origin ${GIT_URL}
      - run: npm install
      - run: npm run deploy
  
workflows:
  version: 2
  node_tests:
    jobs:
      - node_10:
          filters:
            branches:
              only: /.*/
      - node_8:
          filters:
            branches:
              only: /.*/
      - node_6:
          filters:
            branches:
              only: /.*/
      - gh_page_deploy:
          requires:
            - node_10
            - node_8
            - node_6
          filters:
            branches:
              only:
                - gh-pages-deploy-test-branch
